### ISSUE TITLE
`std::exception` should be a virtual base

### ISSUE THREAD

**Issue by lhmouse** [Qihoo360/safe-rules#15]
https://github.com/Qihoo360/safe-rules/blob/4e3d9d63f2553291afa7b6ec2068c9873f9fe3d2/c-cpp-rules.md?plain=1#L9238

Reference: https://www.boost.org/doc/libs/1_81_0/libs/exception/doc/using_virtual_inheritance_in_exception_types.html

**Comment by brotherbeer** [comment]
收到\~ 异常类的菱形继承问题有其特殊性，确实值得重点强调，我们下个版本可能会将这个问题列为单独的一个规则，十分感谢\~
