### ISSUE TITLE
Copy constructors of exceptions shall not throw exceptions

### ISSUE THREAD

**Issue by lhmouse** [Qihoo360/safe-rules#16]
https://github.com/Qihoo360/safe-rules/blob/4e3d9d63f2553291afa7b6ec2068c9873f9fe3d2/c-cpp-rules.md?plain=1#L9516

If the exception handling mechanism handling an uncaught exception (14.6.3) directly invokes a function
that exits via an exception, the function std::terminate is invoked (14.6.2).   (N4917 [except.throw]/7)

**Comment by brotherbeer** [comment]
收到~ 这个问题确实值得重点强调，[ID_exceptionInException](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#exceptioninexception) 的本意也包含拷贝构造函数，但说得不是很明白，我们下个版本会将这个问题列为单独的一个规则，谢谢\~

**Comment by lhmouse** [comment]
这条规则可以商榷的地方很多。

1. 构造异常对象（排除复制构造本身）本身确实可能抛出异常，而且这种情况下会丢失原来的异常上下文。本建议具有事实上的合理性。
2. 考虑 `std::bad_alloc` 并未合理地对该异常到底属于逻辑错误还是运行时错误进行归类，尤其是 [Linux OOM killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html) 生效之情形，`std::bad_alloc` 几乎就完全是由于输入错误导致的（例如 `my_string.resize(-1UL)`）。
3. `what()` 应为 `noexcept`。
