### ISSUE TITLE
标准容器在 move 掉以后，clear 掉重新利用，应为合理的

### ISSUE THREAD

**Issue by lhmouse** [Qihoo360/safe-rules#17]
https://github.com/Qihoo360/safe-rules/blob/4e3d9d63f2553291afa7b6ec2068c9873f9fe3d2/c-cpp-rules.md?plain=1#L1907

**Comment by brotherbeer** [comment]
收到\~ 这条规则的本意也正是如此，在表述上不是很清晰，确实值得优化一下，谢谢\~
