### ISSUE TITLE
使用 cstdio 而不是 stdio.h 不能保证 POSIX 相容性

### ISSUE THREAD

**Issue by lhmouse** [Qihoo360/safe-rules#18]
https://github.com/Qihoo360/safe-rules/blob/4e3d9d63f2553291afa7b6ec2068c9873f9fe3d2/c-cpp-rules.md?plain=1#L2637

例如，`<cstdio>` 不保证提供 `::fileno`。其余几个同理。

**Comment by brotherbeer** [comment]
收到\~ POSIX 的细节暂不作为现阶段的重点，我们不妨以后再讨论这些问题，谢谢\~

**Comment by lhmouse** [comment]
即使不考虑 POSIX，`<cstdio>` 仍然只是 `<stdio.h>` 严格意义上的子集，因此仍然没有推荐 `<cstdio>` 的理由。
唯一的例外是 `<cmath>` `<cstdlib>` 提供了 `abs()` 等重载，这个反而是 `<stdlib.h>` 就没有。

**Comment by brotherbeer** [comment]
并不是推荐 cstdio，只是统一要求在 C++ 中使用 C++ 头文件，cstdio 的例子可能不是很好，我们考虑是否应该换个例子

**Comment by lhmouse** [comment]
实际考虑的是下面这个例子：

### A

```c++
#include <cstddef>
namespace my {
using ::std::size_t;

size_t cpu_cores(void);
const char* cpu_name(void);

}  // namespace my
```

### B

```c++
#include <stddef.h>
namespace my {
using ::size_t;

size_t cpu_cores(void);
const char* cpu_name(void);

}  // namespace my
```

可见，除了 `using` 以外实际上对其它的部分是没有影响的。最终的问题就是 `::size_t` 和 `::std::size_t` 应当建议用哪个。对于 `size_t` 这两个应是一样的，不过更多考虑的是一致性问题。例：

```c++
namespace my {
using ::std::uint32_t;  // cstdint
using ::std::size_t;  // cstddef
using ::DWORD;  // minwindef.h
using ::timespec;  // time.h
using ::ssize_t;  // unistd.h
}  // namespace my
```

**Comment by lhmouse** [comment]
勤劳。
