### ISSUE TITLE
有word的吗

### ISSUE THREAD

**Issue by yourjacob** [Qihoo360/safe-rules#2]
还有公众号？谢了

**Comment by brotherbeer** [comment]
由于字体的版权问题较为繁琐，今年暂不提供Word和PDF版本的文档，不过近期会提供离线的HTML文档。

公众号可搜索“**360质量效能**”，本公众号专注于先进实践经验的分享，也可由此与我们取得联系，谢谢~

**Comment by brotherbeer** [comment]
新年快乐，这个问题先关闭了
