### ISSUE TITLE
C++ 中只要有返回值的函数没有从 `return` 返回就是 UB

### ISSUE THREAD

**Issue by Timothy-Liuxf** [Qihoo360/safe-rules#20]
https://github.com/Qihoo360/safe-rules/blob/b70783c53c7102bb75d70034a2c70f051a3b972e/cpp-ub-list.md?plain=1#L1495

此处“但函数返回值被使用”叙述在 C 语言中是正确的，但是在 C++ 中有误。在 C++ 中，返回值不是 `void` 的函数只能从 `return` 语句返回，否则，无论是否使用返回值，都会产生 UB。C++03 和 C++11 标准 6.6.3(2) 的叙述：

> Flowing off the end of a function is equivalent to a return with no value; this results in undefined behavior in a value-returning function.

并没有对返回值是否使用提出要求。关于此，一个经典的例子是：

```c++
#include <cstdio>

int func(int n) {
    for (int i = 0; i < n; ++i) {
        std::printf("%d\n", i);
    }
}
```

其在 `-O3` 优化等级编译产生汇编代码：<https://gcc.godbolt.org/z/o6YrEx9WE>
可以看到 `for` 直接被 GCC 和 Clang 优化成了死循环 `jmp` 指令，而非预期的进行 `n` 次循环（可能是由于没有 `return` 语句造成编译器找不到函数的返回点而默认 `for` 循环为死循环），符合未定义行为不可预期的特征。

---

但是在 C 语言中，返回值被使用时才会产生未定义行为。在 C11 标准（ISO/IEC 9899: 2011）6.9.1(12) 中规定：

> If the `}` that terminates a function is reached, and the value of the function call is used by the caller, the behavior is undefined.

且 GCC 和 Clang 都能给出符合预期的汇编代码：<https://gcc.godbolt.org/z/9fqdT8eTb>

可见原表述在 C 语言中正确，但是在 C++ 语言中有误。

**Comment by Timothy-Liuxf** [comment]
https://github.com/Qihoo360/safe-rules/blob/b70783c53c7102bb75d70034a2c70f051a3b972e/cpp-ub-list.md?plain=1#L2132

同理，此处也应该是直接产生未定义行为。

**Comment by brotherbeer** [comment]
收到\~ 我们会尽快修正，十分感谢\~
