### ISSUE TITLE
缺少 `signed char`

### ISSUE THREAD

**Issue by Timothy-Liuxf** [Qihoo360/safe-rules#21]
https://github.com/Qihoo360/safe-rules/blob/b70783c53c7102bb75d70034a2c70f051a3b972e/cpp-ub-list.md?plain=1#L739

根据 ISO/IEC 14882: 2003 3.9.1(1) 和 ISO/IEC 14882: 2011 3.9.1(1)：

> Plain `char`, `signed char`, and `unsigned char` are three distinct types

三者是完全不同的类型：

```c++
#include <type_traits>

static_assert(std::is_same<char, signed char>::value == false, "");
static_assert(std::is_same<signed char, unsigned char>::value == false, "");
static_assert(std::is_same<char, unsigned char>::value == false, "");
```

因此应该增加 `signed char`，从而改为：

```markdown
- `char`、`signed char` 或 `unsigned char`
```

**Comment by brotherbeer** [comment]
收到\~ ISO/IEC 14882: 2011 3.10(10) 的原文只提到了 char 和 unsigned char，这是标准的疏漏还是另有深意，我们再研究研究，先按原文翻译吧，谢谢~

![3 10(10)](https://user-images.githubusercontent.com/22165452/217464101-ab8070dd-299e-45bb-af9f-a932ce9ae94a.png)

**Comment by lhmouse** [comment]
ISO C 允许 `signed char`，但是 ISO C++ 未有此条目。

**Comment by Timothy-Liuxf** [comment]
抱歉，这确实是我的疏漏

关于不含 `signed char` 的问题，StackOverflow 上的高赞回答貌似有对其的解释：
<https://stackoverflow.com/questions/21176193/why-c-and-c-hate-signed-char-so-much>

高赞回答的评论里提到的反例 EBCDIC 编码有参考：
+ <http://www.3480-3590-data-conversion.com/article-signed-fields.html>
+ <https://en.wikipedia.org/wiki/EBCDIC#Compatibility_with_ASCII>

**Comment by brotherbeer** [comment]
真是一个有趣的问题\~

**Comment by brotherbeer** [comment]
本文在 [ID_plainBinaryChar](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#plainbinarychar) 中提到了用有符号 char 类型访问二进制数据的弊端，限于篇幅，更深的历史问题和兼容性问题就留给读者继续探索吧~
