### ISSUE TITLE
示例不一定会产生 UB

### ISSUE THREAD

**Issue by Timothy-Liuxf** [Qihoo360/safe-rules#22]
https://github.com/Qihoo360/safe-rules/blob/b70783c53c7102bb75d70034a2c70f051a3b972e/cpp-ub-list.md?plain=1#L1580-L1589

该示例不一定会产生 UB，因为 `bar` 虽然返回 `volatile int*`，但不一定返回 `volatile` 限定的 `int` 对象，例如下面的代码：

```c++
int main() {
    int foo(int& x);
    volatile int* bar(void);
    foo((int&)*bar());  // 无 UB 产生
}

int g0 = 0;
int foo(int& x) { return x = 888; }
volatile int* bar(void) { return &g0; }
```

建议示例可以更加完善，例如给出文字说明，或者给出 `bar` 的实现，等等。

**Comment by brotherbeer** [comment]
收到\~ 我们会尽快修正，十分感谢\~

**Comment by lhmouse** [comment]
确实。是否发生 UB 仅决定最终用于访问对象的左值（去掉引用以后）是否缺少对象的 _定义_ 本来拥有的 `volatile` 限定符，而与中间转换过程无关。
