### ISSUE TITLE
补充volatile使用场景

### ISSUE THREAD

**Issue by onionblack** [Qihoo360/safe-rules#23]
https://github.com/Qihoo360/safe-rules/blob/d06e2da7e91a19ef0cf7a2fdbb0c6009c83226b3/c-cpp-rules.md?plain=1#L6502-L6509

和longjmp有关的变量也得定义成volatile的，longjmp的man:

>   The values of automatic variables are unspecified after a call to longjmp() if they meet all the following criteria:
>    ·  they are local to the function that made the corresponding setjmp(3) call;
>    ·  their values are changed between the calls to setjmp(3) and longjmp(); and
>    ·  they are not declared as volatile.
>   Analogous remarks apply for siglongjmp().

```C
#include <stdio.h>
#include <setjmp.h>

static jmp_buf jb;

void fn(void) { longjmp(jb, 1);}

int main(void)
{
  int i = 1;
  if (!setjmp(jb)) {
    i++;
    fn();
  } else {
    printf("%i\n", i);
  }
  return 0;
}
```
这段代码-O0 -O2输出不一样，就是因为i应该是volatile的，我知道有条规则是不让用longjmp，不过还是说明一下好

**Comment by brotherbeer** [comment]
收到\~ 我们会尽快补充文档
我部代码扫描引擎将所有 volatile 局部变量均判为问题代码，看来如果有 setjmp 则应降低结果的权重
很有指导意义，十分感谢！
