### ISSUE TITLE
把寄存器赋值给指针在驱动里是正常的

### ISSUE THREAD

**Issue by onionblack** [Qihoo360/safe-rules#24]
https://github.com/Qihoo360/safe-rules/blob/d06e2da7e91a19ef0cf7a2fdbb0c6009c83226b3/c-cpp-rules.md?plain=1#L18543-L18550

`int*p=0x1234;`这种在驱动里很正常，不然代码没法写了

我的建议是单独说明一下，嵌入式有关的可以排除

**Comment by brotherbeer** [comment]
收到\~ 在审计中，如果有合理的理由，或者没有更好的方法时，规则也是可以背离的。
这个例子有一定代表性，可以作为“例外”，我们会尽快补充文档，谢谢\~
