### ISSUE TITLE
变量是个端口或者对应寄存器的话只写入是没问题的

### ISSUE THREAD

**Issue by onionblack** [Qihoo360/safe-rules#25]
https://github.com/Qihoo360/safe-rules/blob/d06e2da7e91a19ef0cf7a2fdbb0c6009c83226b3/c-cpp-rules.md?plain=1#L10740-L10744

我的建议是补充说明一下

**Comment by Timothy-Liuxf** [comment]
这种情况对象应该声明为 `volatile`，应该属于第 10746 行和第 6507 行说明的情况吧。

https://github.com/Qihoo360/safe-rules/blob/d06e2da7e91a19ef0cf7a2fdbb0c6009c83226b3/c-cpp-rules.md?plain=1#L10740-L10746

https://github.com/Qihoo360/safe-rules/blob/d06e2da7e91a19ef0cf7a2fdbb0c6009c83226b3/c-cpp-rules.md?plain=1#L6502-L6510

**Comment by onionblack** [comment]
也是，那我先关了，我们有一段代码是这样的
```C
while (1) {
  port = 0;
  port = 1;
}
```
不过port是个对象等号是重载的

**Comment by brotherbeer** [comment]
嗯嗯，可以强调一下“存在写入数据之外的副作用时，可不受本规则约束”
