### ISSUE TITLE
非常好的规范，请问下能推荐下能覆盖这些规则的静态检查工具吗？

### ISSUE THREAD

**Issue by lucky0618** [Qihoo360/safe-rules#26]

**Comment by brotherbeer** [comment]
你好~

本项目是我司代码扫描引擎的规则说明文档，目前没有开源工具能覆盖这些规则

MISRA 规则是本项目的一个重要参考依据，最新版本的 [CppCheck](https://github.com/danmar/cppcheck/releases) 等开源工具可以检查 MISRA C 相关规则，不妨参考一下~
