### ISSUE TITLE
R2.22 存在覆盖不完全的问题

### ISSUE THREAD

**Issue by frederick-vs-ja** [Qihoo360/safe-rules#35]
[R2.22 C++ 代码中禁用 C 内存管理函数](https://github.com/Qihoo360/safe-rules/blob/a0c63a935476dbf59d38cbf4a5c7b59752b7e3b0/c-cpp-rules.md#forbidmallocandfree)

这条其实存在一点问题：C++ 的 `operator new` 和 `operator delete` 甚至依赖操作系统的内存函数同样要纳入这里的考虑。

我们最好改写成“不要直接使用分配、释放裸指针的函数，而是使用 `unique_ptr` 等智能指针及相关的包装工厂函数”。

**Comment by brotherbeer** [comment]
这条规则只强调在 C++ 中不应使用 C 内存管理方法，对于显式 new 和 delete 的使用，由规则 [ID_ownerlessResource](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#ownerlessresource) 约束

**Comment by frederick-vs-ja** [comment]
> 这条规则只强调在 C++ 中不应使用 C 内存管理方法，对于显式 new 和 delete 的使用，由规则 [ID_ownerlessResource](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#ownerlessresource) 约束

这是有一些区别的。 `new` 和 `delete` 表达式（在大多数情况）会分别调用 `operator new` 和 `operator delete`，但前者和后者不同。

**Comment by brotherbeer** [comment]
好的，底层 operator new 和系统资源 API 都应受到限制，我们会介绍地更详细一些
