### ISSUE TITLE
修改“空指针”定义

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#37]
> 空指针表示没有指向任何对象的指针，通过空指针访问对象属于逻辑错误。

#32 改过，但是忘记修改其他地方了，比如：

https://github.com/Qihoo360/safe-rules/blob/a0c63a935476dbf59d38cbf4a5c7b59752b7e3b0/cpp-ub-list.md#55-空指针解引用

**Comment by brotherbeer** [comment]
好的~ 待我们再梳理一遍
