### ISSUE TITLE
R5.1.21 "存在构造、析构的类" 描述不明确

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#38]
> 存在构造、析构或虚函数的类不应采用 struct 关键字

C++标准规定：

>如果没有对类类型提供任何用户声明的构造函数，那么编译器将始终声明一个作为它的类的 inline public 成员的默认构造函数。

>如果不向[类类型](https://zh.cppreference.com/w/cpp/language/class)提供用户声明的析构函数，那么编译器总是会声明一个析构函数作为这个类的 inline public 成员。

原文想表达的应该是：存在**用户显式定义的**构造、析构或虚函数或虚函数的类不应采用 struct 关键字。

---

并且我认为，是用 class 还是 struct，这种依靠开发者们约定的额外意思，不单单是简单的构造析构。

普遍认同的几个约定是： 

- 如果有任何非公开成员，就使用 class 而不是 struct。
- 如果类有一个需要在程序执行过程中永远保持成立的条件，就使用 class

```cpp
struct Pair{  //成员可以独立变化，并且数据一定合法
    string name;
    int volume;
};

class Date{
public:
    //校验 {yy，mm，dd}是不是合法的日期并进行初始化
    Date(int yy, Month mm, char dd);
    // ...
private:
    int y;
    Month m;
    char d;    //日
}
```

值得一提的是，很多库并没有很好的遵守，我们举例 [QPoint](https://doc.qt.io/qt-6/qpoint.html)，[源码](https://codebrowser.dev/qt5/qtbase/src/corelib/tools/qpoint.h.html)。

只能说，都是一些建议了。

**Comment by brotherbeer** [comment]
收到~

这个规则的检查策略有变，忘了更新文档。。
现在要求 standard-layout 且 trivial 的类可以用 struct，否则用 class

按 modern cpp 的理念，下面的用法可能更好，但第二点比较“玄”，难以量化检查

> 如果有任何非公开成员，就使用 class 而不是 struct。
> 如果类有一个需要在程序执行过程中永远保持成立的条件，就使用 class

这两点我也写进去，供人参考吧

**Comment by Mq-b** [comment]
Date 那个示例倒是很明显的“类有一个需要在程序执行过程中永远保持成立的条件”。

并且构造函数有检查参数合法性的功能。

不过有的时候的确可能不好检查，作为参考吧。
