### ISSUE TITLE
R2.20 windows 无法使用 `alloca.h` 标头

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#39]
```cpp
#include <alloca.h>

void fun(size_t n) {
    int* p = (int*)alloca(n * sizeof(int));  // Non-compliant
    if (!p) {
        return;  // Invalid
    }
}
```

无法在 [msvc](https://godbolt.org/z/f185758qY) 通过编译，找不到这个标头。

使用 **malloc.h** [才可以](https://godbolt.org/z/WhYxzv7Ts)。

在 msvc malloc.h 下的 `alloca` 是一个宏，看起来是用作兼容的。

```cpp
#if defined(_CRT_INTERNAL_NONSTDC_NAMES) && _CRT_INTERNAL_NONSTDC_NAMES
    #define alloca _alloca
#endif
```

```cpp
_Ret_notnull_ _Post_writable_byte_size_(_Size)
void* __cdecl _alloca(_In_ size_t _Size);
```

但是改成使用 malloc.h 的话， gcc 又不行了（mingw 的话可以），我觉得有必要稍微更改一下这个示例。

说明在不同的编译器它可能位于不同的头文件中。

以及有必要强调 alloca、strdupa 这种函数不是 C 标准库，也不是 POSIX，而是 [GNU 的扩展](https://www.gnu.org/software/gnulib/manual/html_node/alloca.html) 也被其他的编译器和库广泛支持。

---

> alloca、strdupa 等函数可以在栈上动态分配内存，但分配失败时的行为不受程序控制。

其实我觉得倒也不是完全不受控制，可以说的清楚一些，只是处理很麻烦，调整栈指针事太多了。

比如 [msvc 文档](https://learn.microsoft.com/zh-cn/cpp/c-runtime-library/reference/alloca?view=msvc-170)说的

> 如果在 try 块内调用 _alloca，则必须在 catch 块中调用 [_resetstkoflw](https://learn.microsoft.com/zh-cn/cpp/c-runtime-library/reference/resetstkoflw?view=msvc-170)。

alloca 就是不能用，不用 raii 谁保证你能调用 resetstkoflw，要考虑的事情太多了。

**Comment by brotherbeer** [comment]
好的~ 改成“难以通过标准方法控制”，周末快乐~
