### ISSUE TITLE
下载之后点目录没反应

### ISSUE THREAD

**Issue by LiMuoMuo** [Qihoo360/safe-rules#4]
github上正常下载下来就不行了

**Comment by brotherbeer** [comment]
用的是什么浏览器？现在离线浏览最好使用Typora、Markdown Viewer等工具，后续我们会提高兼容性。

**Comment by LiMuoMuo** [comment]
vscode

**Comment by brotherbeer** [comment]
VSCode需要安装插件“Markdown Preview Enhanced”才能正常显示复杂一些的文档

**Comment by brotherbeer** [comment]
新年快乐，这个问题先关闭了
