### ISSUE TITLE
`R14.18` 的观点非常值得商榷，且解释并不合理

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#40]
> 释放指针后应将指针赋值为空指针

这一原始的规则出现的非常的早，大多数时候也的确没问题，用“空”，表示当前指针的状态，此用法似乎可以追溯到四十年前。

但是教条主义没有价值。其实“释放指针后赋空”，本质上的意思只是因为，空指针字面量等东西可以直接给任何类型的指针，赋值比较方便，然后大家约定了以空表示状态。

事实上如果大家约定的话，完全可以做出一个 `not_null`，比如 `gsl::not_null<T>`，那么为什么要这么做呢？它能带来什么好处？

它的好处其实在文中对例子的描述就已经说明了：

> dealloc 函数释放指针后将其赋值为空指针，delete、free 等接口可以接受空指针，dealloc 函数被反复调用也没有问题，即使相关接口不接受空指针，也可以使问题立即显现出来，便于修正。

**delete、free 等接口可以接受空指针，反复调用也没有问题**。这是标准规定的行为，那么有没有考虑过：

**释放空指针代表本身逻辑已经错误了，因为这个指针是空，而让程序得以继续运行，反而会隐藏错误，在后续产生难以被解决和追溯的问题**。

关于这些争论，互联网上有很多，总而言之，盲目的遵守这些并不合适。

在 [C++Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i12-declare-a-pointer-that-must-not-be-null-as-not_null) 也都有一些关于 `not_null` 说法。

---

如果以上观点有待商榷的话，那么可以先回到规则本身的讲解，也就是这个示例，以及解释是很糟糕的。

>```cpp
>class A {
>    int* p = new int[10];
>public:
>    void dealloc() {
>        delete[] p;
>        p = nullptr;   // Good
>    }
>   ~A() { dealloc(); }
>};
>```

**Comment by brotherbeer** [comment]
这条规则对应国军标 R-1-3-6，SEI CERT 也有相关规则，在某些合规性检查里有硬性要求

本项目的规则不是都要遵守的，有选择性，规则和各种标准的映射列表正在制作中~

**Comment by Mq-b** [comment]
> 如果以上观点有待商榷的话，那么可以先回到规则本身的讲解，也就是这个示例，以及解释是很糟糕的。

修改示例以及解释还是有必要的，示例和解释的侧重点歪了，跑到了 free delete 可以反复操作空指针去了。

**Comment by brotherbeer** [comment]
嗯嗯，解释的应该简练一些，由读者选择
