### ISSUE TITLE
`R8.41` 中对内联函数的描述不正确

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#45]
[原文](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#complexinlinefunction:~:text=%E6%98%AF%E5%90%A6%E5%AF%B9%E5%87%BD%E6%95%B0%E8%BF%9B%E8%A1%8C%E5%86%85%E8%81%94%E4%BC%98%E5%8C%96%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%AE%9A%E4%B9%89%EF%BC%8C%E5%BD%93%E5%87%BD%E6%95%B0%E6%89%A7%E8%A1%8C%E7%9A%84%E5%BC%80%E9%94%80%E8%BF%9C%E5%A4%A7%E4%BA%8E%E8%B0%83%E7%94%A8%E7%9A%84%E5%BC%80%E9%94%80%E6%97%B6%EF%BC%8C%E4%B8%8D%E4%BC%9A%E8%BF%9B%E8%A1%8C%E5%86%85%E8%81%94%E4%BC%98%E5%8C%96%E3%80%82)：

> 是否对函数进行内联优化由实现定义，当函数执行的开销远大于调用的开销时，不会进行内联优化。

我能理解作者想要表达的意思是：“一个函数到底是否内联，最终由编译器自行决定”。

但是这个描述用词，显然是有问题的：“**内联优化由实现定义**”，“实现定义”这个词语，不应该用在这里，它通常不是用来表达这种意思的。

[cppreference](https://zh.cppreference.com/w/cpp/language/ub#:~:text=%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%AE%9A%E4%B9%89%E7%9A%84%E8%A1%8C%E4%B8%BA%EF%BC%88implementation%2Ddefined%20behavior%EF%BC%89%E2%80%94%E2%80%94%E7%A8%8B%E5%BA%8F%E7%9A%84%E8%A1%8C%E4%B8%BA%E9%9A%8F%E5%AE%9E%E7%8E%B0%E8%80%8C%E5%8F%98%E5%8A%A8%EF%BC%8C%E9%81%B5%E4%BB%8E%E6%A0%87%E5%87%86%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%BF%85%E9%A1%BB%E4%B8%BA%E6%AF%8F%E4%B8%AA%E8%BF%99%E6%A0%B7%E7%9A%84%E8%A1%8C%E4%B8%BA%E7%9A%84%E6%95%88%E6%9E%9C%E6%8F%90%E4%BE%9B%E6%96%87%E6%A1%A3%E3%80%82%E4%BE%8B%E5%A6%82%20std%3A%3Asize_t%20%E7%9A%84%E7%B1%BB%E5%9E%8B%E6%88%96%E6%AF%8F%E4%B8%AA%E5%AD%97%E8%8A%82%E7%9A%84%E4%BD%8D%E6%95%B0%EF%BC%8C%E6%88%96%E8%80%85%20std%3A%3Abad_alloc%3A%3Awhat%20%E7%9A%84%E6%96%87%E6%9C%AC%E3%80%82%E7%94%B1%E5%AE%9E%E7%8E%B0%E5%AE%9A%E4%B9%89%E7%9A%84%E8%A1%8C%E4%B8%BA%E7%9A%84%E4%B8%80%E4%B8%AA%E5%AD%90%E9%9B%86%E6%98%AF%E6%9C%AC%E5%9C%B0%E7%8E%AF%E5%A2%83%E7%89%B9%E5%AE%9A%E8%A1%8C%E4%B8%BA%EF%BC%88locale%2Dspecific%20behavior%EF%BC%89%EF%BC%8C%E5%AE%83%E5%8F%96%E5%86%B3%E4%BA%8E%E5%AE%9E%E7%8E%B0%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E6%9C%AC%E5%9C%B0%E7%8E%AF%E5%A2%83%E3%80%82)：

> 由实现定义的行为（implementation-defined behavior）——程序的行为随实现而变动，遵从标准的实现必须为每个这样的行为的效果提供文档。例如 [std::size_t](https://zh.cppreference.com/w/cpp/types/size_t) 的类型或每个字节的位数，或者 [std::bad_alloc::what](https://zh.cppreference.com/w/cpp/memory/new/bad_alloc) 的文本。由实现定义的行为的一个子集是本地环境特定行为（locale-specific behavior），它取决于实现所提供的[本地环境](https://zh.cppreference.com/w/cpp/locale)。

可以参考[微软文档](https://learn.microsoft.com/zh-cn/cpp/cpp/inline-functions-cpp?view=msvc-170#:~:text=%E5%86%85%E8%81%94%E4%BB%A3%E7%A0%81%E6%9B%BF%E6%8D%A2%E6%93%8D%E4%BD%9C%E7%94%B1%E7%BC%96%E8%AF%91%E5%99%A8%E8%87%AA%E8%A1%8C%E5%86%B3%E5%AE%9A%E3%80%82%20%E4%BE%8B%E5%A6%82%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9F%90%E4%B8%AA%E5%87%BD%E6%95%B0%E7%9A%84%E5%9C%B0%E5%9D%80%E5%B7%B2%E8%A2%AB%E5%8D%A0%E7%94%A8%E6%88%96%E7%BC%96%E8%AF%91%E5%99%A8%E5%88%A4%E5%AE%9A%E5%87%BD%E6%95%B0%E8%BF%87%E5%A4%A7%EF%BC%8C%E5%88%99%E7%BC%96%E8%AF%91%E5%99%A8%E4%B8%8D%E4%BC%9A%E5%86%85%E8%81%94%E8%AF%A5%E5%87%BD%E6%95%B0%E3%80%82)的说法：

> 内联代码替换操作由**编译器自行决定**。 例如，如果某个函数的地址已被占用或编译器判定函数过大，则编译器不会内联该函数。

**Comment by frederick-vs-ja** [comment]
如果按标准习惯的话会说“未指定（unspecified）”。因为内联替换是不影响标准语义的，没有标准保证的方法确定它是否发生。

不过我想资料中说“由编译器决定”或者“由实现决定”就好。（理论上实现可以不包含编译器而只有解释器，但这毕竟不太需要考虑。）

**Comment by brotherbeer** [comment]
很有道理~

**Comment by brotherbeer** [comment]
C11 是这么说的 6.7.4(6)：
>  A function declared with an inline function specifier is an inline function. Making a function an inline function suggests that calls to the function be as fast as possible.138) The extent to which such suggestions are effective is **implementation-defined**.

但编译器一般也没公开具体是怎样的处理方法，所以为了避免争议，还是改成“**编译器自行决定**”吧
