### ISSUE TITLE
`R14.24` “指针运算应使用数组下标的方式” 是否没考虑 `p[0]`、`*p`

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#46]
此规则是否没考虑过 `*` 运算符？

```cpp
T* p = new T{};
*p;            // 合理
p[0];          // 完全等价于 *(p + 0)
```

> 内建下标表达式 E1[E2] 除了[值类别](https://zh.cppreference.com/w/cpp/language/value_category)（见下文）和[求值顺序](https://zh.cppreference.com/w/cpp/language/eval_order) (C++17 起)之外与表达式 *(E1 + E2) 严格等同

我个人认为，如果是像我给出的示例一样，只是指针指向了一个对象（使用 `new` 而非 `new[]`），使用 `*`，要远好于 `[0]`。

这在于我认为使用 `[]` 有**暗示**：*这是一个“数组”，或者说这个指针指向了一片连续的内存*。而 `*` 则**暗示**：*这是一个指针*。

这种略微抽象但是很常见的意思。

这就如同，一个 `int arr[10]` 数组对象，我们要访问它的第一个元素，应该是 `arr[0]`，而不是 `*arr`，虽然这也可行，但是暗示的意思很怪，*阅读此代码下意识会认为这是个指针*。

---

说来说去，表达的意思也很简单，“*指针运算应使用数组下标的方式*”，这种规则，并不适合完全遵守，禁不起实际的推敲。

规则中提到的示例：

>```cpp
>int a[10];
>int* p;
>
>p = a + 1;      // Non-compliant
>p = &a[1];      // Compliant
>
>*(p + 1) = 0;   // Non-compliant
>p[1] = 0;       // Compliant
>
>p = p + 1;      // Non-compliant
>p++;            // Compliant
>p = &p[1];      // Compliant
>```

不够完善。

**Comment by brotherbeer** [comment]
“指针运算”在这里专指指针与整数的加减运算，嵌入式领域比较看重这条规则。

*p 和 p[0] 不受这条规则限制，不过可以说地更明白一些

**Comment by brotherbeer** [comment]
未指向数组元素的指针用 p[0] 这种方式确实很怪，值得强调一下，我觉得放在[这条规则](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#illptrarithmetic)里比较好。

**Comment by frederick-vs-ja** [comment]
> 我个人认为，如果是像我给出的示例一样，只是指针指向了一个对象（使用 `new` 而非 `new[]`），使用 `*`，要远好于 `[0]`。
> 
> 这在于我认为使用 `[]` 有**暗示**：_这是一个“数组”，或者说这个指针指向了一片连续的内存_。而 `*` 则**暗示**：_这是一个指针_。

用 `new[]` 时得到的结果也是指针，我们不能直接得到指代 new 表达式所创建的数组的表达式。

另外我觉得 R14.8 的标题对标准存在一些误解。在指针算术和比较中，指向非元素对象的指针被视为指向有 1 个元素的数组首元素的指针。

**Comment by Mq-b** [comment]
> > 我个人认为，如果是像我给出的示例一样，只是指针指向了一个对象（使用 `new` 而非 `new[]`），使用 `*`，要远好于 `[0]`。
> > 这在于我认为使用 `[]` 有**暗示**：_这是一个“数组”，或者说这个指针指向了一片连续的内存_。而 `*` 则**暗示**：_这是一个指针_。
> 
> 用 `new[]` 时得到的结果也是指针，我们不能直接得到指代 new 表达式所创建的数组的表达式。
> 

我已经强调了：“暗示*这是一个“数组”，或者说这个指针指向了一片连续的内存*”，我知道 `new[]` 的结果也是指针。

**Comment by Mq-b** [comment]
> “指针运算”在这里专指指针与整数的加减运算，嵌入式领域比较看重这条规则。
> 
> *p 和 p[0] 不受这条规则限制，不过可以说地更明白一些

嗯，可以强调一下。

**Comment by Mq-b** [comment]
> 未指向数组元素的指针用 p[0] 这种方式确实很怪，值得强调一下，我觉得放在[这条规则](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#illptrarithmetic)里比较好。

都可以强调一下，因为 `R14.24` 就叫：“指针运算应使用数组下标的方式”，除非改一下说法。

**Comment by frederick-vs-ja** [comment]
> > > 我个人认为，如果是像我给出的示例一样，只是指针指向了一个对象（使用 `new` 而非 `new[]`），使用 `*`，要远好于 `[0]`。
> > > 这在于我认为使用 `[]` 有**暗示**：_这是一个“数组”，或者说这个指针指向了一片连续的内存_。而 `*` 则**暗示**：_这是一个指针_。
> > 
> > 
> > 用 `new[]` 时得到的结果也是指针，我们不能直接得到指代 new 表达式所创建的数组的表达式。
> 
> 我已经强调了：“暗示_这是一个“数组”，或者说这个指针指向了一片连续的内存_”，我知道 `new[]` 的结果也是指针。

应该说这里*有*一个数组而 `p` 指向数组首元素，涉及 `new[]` 的情况下通常不会用到指代数组的表达式。

**Comment by Mq-b** [comment]
> > > > 我个人认为，如果是像我给出的示例一样，只是指针指向了一个对象（使用 `new` 而非 `new[]`），使用 `*`，要远好于 `[0]`。
> > > > 这在于我认为使用 `[]` 有**暗示**：_这是一个“数组”，或者说这个指针指向了一片连续的内存_。而 `*` 则**暗示**：_这是一个指针_。
> > > 
> > > 
> > > 用 `new[]` 时得到的结果也是指针，我们不能直接得到指代 new 表达式所创建的数组的表达式。
> > 
> > 
> > 我已经强调了：“暗示_这是一个“数组”，或者说这个指针指向了一片连续的内存_”，我知道 `new[]` 的结果也是指针。
> 
> 应该说这里_有_一个数组而 `p` 指向数组首元素，涉及 `new[]` 的情况下通常不会用到指代数组的表达式。

倒也不一定要是“首元素”，虽然不这样会很抽象，反正意思就这样。
