### ISSUE TITLE
`SIG_ATOMIC_MIN` 与 `SIG_ATOMIC_MAX` 的问题

### ISSUE THREAD

**Issue by frederick-vs-ja** [Qihoo360/safe-rules#47]
[R15.1 避免异步信号处理产生的数据竞争](https://github.com/Qihoo360/safe-rules/blob/main/c-cpp-rules.md#r151-%E9%81%BF%E5%85%8D%E5%BC%82%E6%AD%A5%E4%BF%A1%E5%8F%B7%E5%A4%84%E7%90%86%E4%BA%A7%E7%94%9F%E7%9A%84%E6%95%B0%E6%8D%AE%E7%AB%9E%E4%BA%89)

> 用 SIG_ATOMIC_MIN 和 SIG_ATOMIC_MAX 之间的值对 sig_atomic_t 类型的对象赋值可以保证原子性，超出范围的赋值，或赋值之外的操作不能保证原子性，需要避免。

这里描述存在误导。`SIG_ATOMIC_MIN` 与 `SIG_ATOMIC_MAX` 本来就是 `sig_atomic_t` 类型的最小值与最大值，不存在此范围外的值。如果将更大范围的整数值赋值给 `sig_atomic_t`，那么在赋值**前**会发生隐式转换。

**Comment by brotherbeer** [comment]
很有道理~
