### ISSUE TITLE
目录链接失效

### ISSUE THREAD

**Issue by wuxvincent** [Qihoo360/safe-rules#5]
如图
![e0](https://user-images.githubusercontent.com/96398984/147431055-635f782e-6d29-439b-a3cc-069c858dd11b.png)

**Comment by brotherbeer** [comment]
这应该是中括号造成的兼容性问题，应把中括号去掉，换一种更简练的表达

**Comment by brotherbeer** [comment]
新年快乐，这个问题先关闭了
