### ISSUE TITLE
`R3.1.2` “include 指令中禁用不合规的字符”中的建议描述，不妥

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#51]
最后一句话，原文：

> 另外，某些平台的文件路径不区分大小写，**建议在头文件名称中只使用小写字母以提高可移植性**。

windows 的确不区分大小写，以至于当我想 `include<vector>` 的时候，实际也可以写成 `include<VecTor>`（当然，这毫无意义）。我们要说的是“建议在头文件名称中只使用小写字母以提高可移植性”，其实这**基本是不可能的**。

- **头文件的内容应该完全按照要引用的文件的格式**。

如果按照建议：“**在头文件名称中只使用小写字母**”：

```cpp
// Ab.h
#include<iostream>
static void f1(){
    std::puts("Ab.h");
}
```

```cpp
// main.cpp
#include"ab.h" // 小写

int main(){
    f1();
}
```

```
 g++ main.cpp -o main
```

那么此段代码只能在 windows 等不区分文件大小写的环境下通过编译，如果在 `Linux` 等区分的环境，则无法通过编译。

**Comment by brotherbeer** [comment]
这个是建议文件以小写字母命名，而不是说一定要在include指令里写小写字母。可能表达上有点模糊，我改进一下吧

**Comment by Mq-b** [comment]
> 这个是建议文件以小写字母命名，而不是说一定要在include指令里写小写字母。可能表达上有点模糊，我改进一下吧

合理。
