### ISSUE TITLE
`R14.1` “避免空指针解引用” 空指针的描述可以修改

### ISSUE THREAD

**Issue by Mq-b** [Qihoo360/safe-rules#53]
原文：

> 使用 nullptr、NULL、0 等常量初始化的指针是空指针

应改为：“使用 nullptr、NULL、0 这些*空指针常量*初始化的指针是空指针”。

建议强调“空指针常量”，其实考虑字面量这种说法似乎也可行。

“**等**”，事实上没有额外的空指针常量了。

这里的“**等**”不可能表达的是：“*[零初始化](https://zh.cppreference.com/w/cpp/language/zero_initialization)和[值初始化](https://zh.cppreference.com/w/cpp/language/value_initialization)也初始化指针为它对应的空值。*”

除非表达的是：“*[std::nullptr_t](https://zh.cppreference.com/w/cpp/types/nullptr_t) 类型的纯右值*”，然而它通常就是 `nullptr`。除非......：

```cpp
int* p = std::nullptr_t{};
```

然而感觉这也不太可能是原文表达的“常量”。

---

写了半天感觉莫名其妙，因为可以简单的描述：

> **空指针是值为空的指针（通常使用空指针字面量 nullptr，或空指针常量 0、NULL 进行初始化）**

之前提过：https://github.com/Qihoo360/safe-rules/pull/32

**Comment by brotherbeer** [comment]
0L、'\0'  甚至 false、1 - 1，以及 C 语言的 (void*)0 ，也包括 C++ 的 nullptr_t{}，都可以作为空指针常量，只是不建议这么用，所以文中用“等常量”来概括了。

当然，“空指针常量” 这个概念是值得进一步强调的，我们后续会进行更严谨的阐述。

**Comment by Mq-b** [comment]
这是考虑 C 语言导致的，行吧。

**Comment by frederick-vs-ja** [comment]
> 0L、'\0' 甚至 false、1 - 1，以及 C 语言的 (void*)0 ，也包括 C++ 的 nullptr_t{}，都可以作为空指针常量，只是不建议这么用，所以文中用“等常量”来概括了。
> 
> 当然，“空指针常量” 这个概念是值得进一步强调的，我们后续会进行更严谨的阐述。

注意 C++11/[CWG903](https://cplusplus.github.io/CWG/issues/903.html) 起 `'\0'`、 `false` 及 `1 - 1` 不再被允许为空指针常量了；C 中仍然允许这些表达式作为空指针常量。

**Comment by brotherbeer** [comment]
> > 0L、'\0' 甚至 false、1 - 1，以及 C 语言的 (void*)0 ，也包括 C++ 的 nullptr_t{}，都可以作为空指针常量，只是不建议这么用，所以文中用“等常量”来概括了。
> > 当然，“空指针常量” 这个概念是值得进一步强调的，我们后续会进行更严谨的阐述。
> 
> 注意 C++11/[CWG903](https://cplusplus.github.io/CWG/issues/903.html) 起 `'\0'`、 `false` 及 `1 - 1` 不再被允许为空指针常量了；C 中仍然允许这些表达式作为空指针常量。

收到~
