### ISSUE TITLE
希望举某个规则示例时，该示例也能符合全文其他地方要求的规范，统一风格

### ISSUE THREAD

**Issue by plopop** [Qihoo360/safe-rules#56]
比如4.1要求全局变量名不能太短，在4.10的示例中推荐了单个字符变量名，对随手翻阅党不友好😂

R4.1 全局名称应遵循合理的命名方式：
// In global scope
const int i = 0;     // Non-compliant, name too short
typedef int t;       // Non-compliant, name too short
class A { .... };    // Non-compliant, name too short
...

R4.10 全局对象只应为常量或静态对象：
// In global scope
...
const int k = 0;    // Compliant

**Comment by brotherbeer** [comment]
已修正，谢谢~
