### ISSUE TITLE
部分图标失效

### ISSUE THREAD

**Issue by wuxvincent** [Qihoo360/safe-rules#6]
线上
![e1](https://user-images.githubusercontent.com/96398984/147431302-2dc16958-3c61-4511-80a9-1ab553a5b68c.png)

release
![e2](https://user-images.githubusercontent.com/96398984/147431322-735624ea-051f-45c9-83cf-a4f5db88c35d.png)

**Comment by brotherbeer** [comment]
图标是emoji表情，这个表情比较新，可能不是所有阅读器都能支持，近期我们会提供一个离线HTML文档，解决这些兼容性问题

**Comment by brotherbeer** [comment]
新年快乐，这个问题先关闭了
