### ISSUE TITLE
几点疑问

### ISSUE THREAD

**Issue by LiuLingLing1217** [Qihoo360/safe-rules#9]
右子表达不应有副作用，求余运算符左右子表达重复
这些少写了式字？

R9.6.2和R9.6.3说的是catch，但被分到了try一节
应该放到catch那节吧？

**Comment by brotherbeer** [comment]
收到\~ 相关笔误已经在本次提交中一并处理了，十分感谢~

**Comment by brotherbeer** [comment]
第二点很有道理，try和catch本为一体，不应分开，我们也打算将这二节合为一节~
